### ISSUE TITLE
Unable to launch PartiQL/JSON/YAML server after certain upgrade 

### ISSUE THREAD

**Issue by XuechunHHH** [aws/language-servers#374]
**Describe the bug**
PartiQL / JSON / YAML server are not able to launch after #328 and #326. 

In #328, some renaming there got a bit missed up in [partiql](https://github.com/aws/language-servers/blob/main/.vscode/launch.json#L60) and in [JSON/YAML](https://github.com/aws/language-servers/blob/main/.vscode/launch.json#L48). It seems to be `"LSP_SERVER": "${workspaceFolder}/app/aws-lsp-partiql-runtimes/build/aws-lsp-partiql-binary.js"` for PartiQL server and `"LSP_SERVER": "${workspaceFolder}/app/aws-lsp-yaml-runtimes/build/aws-lsp-yaml-standalone.js"` instead.

Then after the change of #326, these three servers just can't be launched via `run and debug`. 

**To reproduce**

1. Check out to head 9226fb4ed10dc54f1719b14a5b1dac1807641f79 (#326).
2. Go to file `.vscode/launch.json` line 60.
3. Change the line to `"LSP_SERVER": "${workspaceFolder}/app/aws-lsp-partiql-runtimes/build/aws-lsp-partiql-binary.js"`.
4. Run `npm install`and `npm run package` in the terminal.
5. Go to `RUN AND DEBUG` mode, switch to PartiQL Server and click the green RUN button.
6. AWS Documents Language Server can't be launched.

**Expected behavior**
<img width="600" alt="Screenshot 2024-07-08 at 1 09 29 PM" src="https://github.com/aws/language-servers/assets/122423248/24a670f8-9326-40ff-898c-9b391c293c04">

**Screenshots for Errors**
<img width="600" alt="Screenshot 2024-07-08 at 1 20 02 PM" src="https://github.com/aws/language-servers/assets/122423248/f3b68ba0-5792-4dbd-a356-982414fab14a">

**Your Environment**

-   OS: macOS Sonoma Version 14.5

**Comment by rahmaniaam** [comment]
Thanks for submitting the issue.

The fix (https://github.com/aws/language-servers/pull/376) has been merged to main. Please check if all is working well for you now
